### ISSUE TITLE
does this work with exalt data?

### ISSUE THREAD

**Issue by Mizork** [Mystery3/RotMG-SpriteRenderer#1]
Exalt data seems to be in a new format like an atlas, contains spritesheet.json and mapObjects.png as well as some others, can be seen either from https://www.haizor.net/rotmg/assets/production/atlases/  or  from  https://rotmg.extacy.cc/production/client/current/extracted_assets/  (inside folders Sprite, Texture2D and TextAsset).

Is there a way to render items/tiles based on that newer format? Because otherwise, I always have to wait for someone to extract the separate xml and sprite sheets, and looking at the spritesheet.json file, even tho it doesnt tell what item is what in terms of a name, it does seem to contain indexes and dimensions/locations for sprites, the only question is how to structure all that into separate sheets, cause the json does mention the sheet name, like lofiObj3, etc, but nothing else, and since the mapObjects contains the sprites all over the place, I am not sure your tool can help or am I mistaking?

Thanks!

**Comment by Mystery3** [comment]
My tool can't be used with exalt data yet, but I am working on supporting it

**Comment by Mizork** [comment]
Thank you for replying, will be awesome if you can one day, thanks for this!

**Comment by Mystery3** [comment]
I probably won't be able to do this in one day or any time soon since I am waiting for Deca to release their changes regarding skin animations and such. Once I can see how they do it I can adjust my tool accordingly and then I will include atlas support.

**Comment by Mystery3** [comment]
https://drive.google.com/file/d/1K9k-n0PvbjWHHbQHMXO3C2Je_d2Gn1hQ/view?usp=sharing
heres a quick toolie that can render single sprites from atlas files. its very rudimentary and limited but it is can get you a sprite from an xml id. it has no gui, you run it from cmd.exe or something similar. use "python gamesprites.py help" for more info. you will need at least Python 3.9 and the PIL (Pillow) library. I will reuse some of this code later when I implement it into the main tool (eventually...)
